# Generated by Django 4.2.4 on 2023-09-14 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название/тема')),
                ('text', models.TextField(verbose_name='текст')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Mailin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='название рассылки')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='время старта рассылки')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='время остановки рассылки')),
                ('interval', models.CharField(choices=[('daily', 'ежедневно'), ('weekly', 'еженедельно'), ('monthly', 'ежемесячно')], max_length=10, verbose_name='интервал рассылки')),
                ('status', models.CharField(blank=True, default='pending', max_length=10, verbose_name='статус')),
                ('message', models.ManyToManyField(blank=True, null=True, to='mailing.message', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='электронная почта')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('mailin', models.ManyToManyField(to='mailing.mailin', verbose_name='рассылки')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='AttemptsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lust_time', models.DateTimeField(auto_now_add=True, verbose_name='дата и время')),
                ('status', models.BooleanField(verbose_name='статус отправки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервиса')),
                ('massage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
            },
        ),
    ]
