# Generated by Django 4.2.4 on 2023-09-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_client_owner_mailin_owner_message_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attemptslog',
            old_name='massage',
            new_name='message',
        ),
    ]
