# Generated by Django 4.2.4 on 2023-11-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_rename_massage_attemptslog_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attemptslog',
            old_name='lust_time',
            new_name='last_time',
        ),
    ]
